package com.portal.DTO;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import com.portal.entities.Designation;
import com.portal.entities.Location;
import com.portal.entities.Role;

public class EmployeeOutDTO {
    /**
     * .* Autogenerated Id .
     */
    private Long id;
    /**
     * . employee id of employee.
     */
    private String empId;
    /**
     * name of employee.
     */
    private String name;
    /**
     * email id of employee.
     */
    private String email;
    /**
     * date of birth of employee.
     */

    private String dob;
    /**
     * date of joining of employee.
     */

    private String doj;
    /**
     * location of employee.
     */

    private Location location;
    /**
     * designation of employee.
     */

    private Designation designation;
    /**
     * contact number of employee.
     */
    private String contactNumber;
    /**
     * role of employee.
     */

    private Role role;

    /**
     * projectId of employee.
     */
    private Long projectId;
    /**
     * project projectName.
     */
    private String projectName;
    /**
     * skills of employee.
     */
    private List<String> skills;
    /**
     * manager id of employee.
     */

    private String manager;
    /**
     * manager of employee.
     */

    private Long managerId;

    /**
     * @return the id
     */
    public Long getId() {
        return id;
    }

    /**
     * @param idParam the id to set
     */
    public void setId(final Long idParam) {
        this.id = idParam;
    }

    /**
     * @return the empId
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * @param empIdParam the empId to set
     */
    public void setEmpId(final String empIdParam) {
        this.empId = empIdParam;
    }

    /**
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * @param nameParam the name to set
     */
    public void setName(final String nameParam) {
        this.name = nameParam;
    }

    /**
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param emailParam the email to set
     */
    public void setEmail(final String emailParam) {
        this.email = emailParam;
    }

    /**
     * @return the dob
     */
    public String getDob() {
        return dob;
    }

    /**
     * @param dobParam the dob to set
     */
    public void setDob(final String dobParam) {
        this.dob = dobParam;
    }

    /**
     * @return the doj
     */
    public String getDoj() {
        return doj;
    }

    /**
     * @param dojParam the doj to set
     */
    public void setDoj(final String dojParam) {
        this.doj = dojParam;
    }

    /**
     * @return the location
     */
    public Location getLocation() {
        return location;
    }

    /**
     * @param locationParam the location to set
     */
    public void setLocation(final Location locationParam) {
        this.location = locationParam;
    }

    /**
     * @return the designation
     */
    public Designation getDesignation() {
        return designation;
    }

    /**
     * @param designationParam the designation to set
     */
    public void setDesignation(final Designation designationParam) {
        this.designation = designationParam;
    }

    /**
     * @return the contactNumber
     */
    public String getContactNumber() {
        return contactNumber;
    }

    /**
     * @param contactNumberParam the contactNumber to set
     */
    public void setContactNumber(final String contactNumberParam) {
        this.contactNumber = contactNumberParam;
    }

    /**
     * @return the role
     */
    public Role getRole() {
        return role;
    }

    /**
     * @param roleParam the role to set
     */
    public void setRole(final Role roleParam) {
        this.role = roleParam;
    }

    /**
     * @return the projectId
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * @param projectIdParam the projectId to set
     */
    public void setProjectId(final Long projectIdParam) {
        this.projectId = projectIdParam;
    }

    /**
     * Gets the list of skills possessed by the admin.
     * @return The list of skills.
     */
    public List<String> getSkills() {
        return new ArrayList<>(skills);
    }

    /**
     * Sets the list of skills possessed by the admin.
     * @param skillsParam The list of skills.
     */
    public final void setSkills(final List<String> skillsParam) {
        if (skillsParam != null) {
            this.skills = new ArrayList<>(skillsParam);
        } else {
            this.skills = null;
        }
    }

    /**
     * @return the manager
     */
    public String getManager() {
        return manager;
    }

    /**
     * @param managerParam the manager to set
     */
    public void setManager(final String managerParam) {
        this.manager = managerParam;
    }

    /**
     * @return the managerId
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * @param managerIdParam the managerId to set
     */
    public void setManagerId(final Long managerIdParam) {
        this.managerId = managerIdParam;
    }

    /**
     * @return the projectName
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * @param projectNameParam the projectName to set
     */
    public void setProjectName(final String projectNameParam) {
        this.projectName = projectNameParam;
    }

    /**
     * Generates a hash code for this EmployeeOutDTO based on its attributes.
     * @return A hash code value for this EmployeeOutDTO.
     */
    @Override
    public int hashCode() {
        return Objects.hash(contactNumber, designation, dob, doj, email,
                empId, id, location, manager, managerId, name, projectId,
                projectName, role, skills);
    }

    /**
     * Compares this EmployeeOutDTO with the specified object for equality.
     * @param obj The object to compare with this EmployeeOutDTO.
     * @return {@code true} if the objects are equal, {@code false} otherwise.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        EmployeeOutDTO other = (EmployeeOutDTO) obj;
        return Objects.equals(contactNumber, other.contactNumber)
                && designation == other.designation
                && Objects.equals(dob, other.dob)
                && Objects.equals(doj, other.doj)
                && Objects.equals(email, other.email)
                && Objects.equals(empId, other.empId)
                && Objects.equals(id, other.id)
                && location == other.location
                && Objects.equals(manager, other.manager)
                && Objects.equals(managerId, other.managerId)
                && Objects.equals(name, other.name)
                && Objects.equals(projectId, other.projectId)
                && Objects.equals(projectName, other.projectName)
                && role == other.role
                && Objects.equals(skills, other.skills);
    }


    /**
     * Returns a string representation of the EmployeeOutDTO object.
     * @return A string representation of this EmployeeOutDTO.
     */
    @Override
    public String toString() {
        return "EmployeeOutDTO [Id=" + id + ", empId=" + empId + ", name="
                + name + ", email=" + email + ", dob=" + dob + ", doj="
                + doj + ", location=" + location + ", designation="
                + designation + ", contactNumber=" + contactNumber
                + ", role=" + role + ", projectId=" + projectId
                + ", skills=" + skills + ", manager=" + manager
                + ", managerId=" + managerId + "]";
    }

}
