package com.portal.DTO;

import java.util.Objects;

/**
 * Response dto to give all request resourse.
 */
public class ResponseAllRequestDTO {
	   /**
     * Autogenerated primary key field.
     */
    private Long id;
    /**
     * Manager id.
     */
    private Long managerId;
    /**
     * Employee id.
     */
    private Long employeeId;
    /**
     * Comment for request resourse.
     */
    private String comment;
    /**
     * Project Id.
     */
    private Long projectId;
    /**
     * Employee name.
     */
    private String empName;
    /**
     * Manager Name.
     */
    private String managerName;
    /**
     * project Name.
     */
    private String projectName;

    /**
     * @return the id.
     */
    public Long getId() {
        return id;
    }

    /**
     * @param resourseId the id to set.
     */
    public void setId(final Long resourseId) {
        this.id = resourseId;
    }

    /**
     * @return the managerId.
     */
    public Long getManagerId() {
        return managerId;
    }

    /**
     * @param resourseManagerId the managerId to set.
     */
    public void setManagerId(final Long resourseManagerId) {
        this.managerId = resourseManagerId;
    }

    /**
     * @return the employeeId.
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * @param requestEmployeeId the employeeId to set.
     */
    public void setEmployeeId(final Long requestEmployeeId) {
        this.employeeId = requestEmployeeId;
    }

    /**
     * @return the comment.
     */
    public String getComment() {
        return comment;
    }

    /**
     * @param resourseComment the comment to set.
     */
    public void setComment(final String resourseComment) {
        this.comment = resourseComment;
    }

    /**
     * @return the projectId.
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * @param Long1 the projectId to set.
     */
    public void setProjectId(final Long Long1) {
        this.projectId = Long1;
    }

    /**
     * @return the empName.
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * @param requestEmpName the empName to set.
     */
    public void setEmpName(final String requestEmpName) {
        this.empName = requestEmpName;
    }

    /**
     * @return the managerName.
     */
    public String getManagerName() {
        return managerName;
    }

    /**
     * @param requestManagerName the managerName to set.
     */
    public void setManagerName(final String requestManagerName) {
        this.managerName = requestManagerName;
    }

    /**
     * @return the projectName.
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * @param requestProjectName the projectName to set.
     */
    public void setProjectName(final String requestProjectName) {
        this.projectName = requestProjectName;
    }

    /**
     * Used to generate hashcode.
     */
    @Override
    public int hashCode() {
        return Objects.hash(comment, empName, employeeId, id, managerId,
                managerName, projectId, projectName);
    }

    /**
     * Used to compare objects.
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        ResponseAllRequestDTO other = (ResponseAllRequestDTO) obj;
        return Objects.equals(comment, other.comment)
                && Objects.equals(empName, other.empName)
                && Objects.equals(employeeId, other.employeeId)
                && Objects.equals(id, other.id)
                && Objects.equals(managerId, other.managerId)
                && Objects.equals(managerName, other.managerName)
                && Objects.equals(projectId, other.projectId)
                && Objects.equals(projectName, other.projectName);
    }

    /**
     * Used to get values of object.
     */
    @Override
    public String toString() {
        return "ResponseAllRequestDto [id=" + id + ", managerId=" + managerId
                + ", employeeId=" + employeeId + ", comment=" + comment
                + ", projectId=" + projectId + ", empName=" + empName
                + ", managerName=" + managerName + ", projectName="
                + projectName + "]";
    }
}
